// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1678433691);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1678443379);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1678433570);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1678347079);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1678433811);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1678433692);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230131132728");
user_pref("extensions.lastAppVersion", "102.7.1");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"651decf2-4d10-42b2-bbb3-6227a976b737\"}");
user_pref("idle.lastDailyNotification", 1678347204);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "fb014868-aee7-43f9-90a3-4ca4576d581");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1678347204);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -1537);
user_pref("services.settings.last_update_seconds", 1678348707);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1678348707);
user_pref("services.settings.thunderbird.search-config.last_check", 1678348707);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1678348707);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1678347204);
user_pref("toolkit.telemetry.cachedClientID", "346cc5dd-f397-40ce-a3e9-9f0ea1804995");
user_pref("toolkit.telemetry.previousBuildID", "20230131132728");
